name: Lint

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: "flake8_py3" # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run flake8 on your PR - with annotations!
        uses: tayfun/flake8-your-pr@1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
